### ISSUE TITLE
Czech translate

### ISSUE THREAD

**Issue by LabBrab** [antontimmermans/MOMEITM#1]
Hi, I translated the script "Eyes behind the Mirror" into Czech. Can translation be added to valkyrie?

**Comment by antontimmermans** [comment]
HI @LabBrab,

That is fast!  :)
I can surely add the translation to the scenario. If you attach your translation to this issue, I will pick it up and include it.

Please be aware that future updates of this scenario will have alternative layouts for the end game. I am currently working on a museum (SoA) but later I will also include a temple (PotS) and a Ship (HJ). Is it OK if I contact you for translating those parts too?

Best regards,
Anton

**Comment by LabBrab** [comment]
[Localization.Czech.txt](https://github.com/antontimmermans/MOMEITM/files/10812114/Localization.Czech.txt)

Hi Anton,

I will definitely be happy to participate in the translation of other alternative endings.

Best regards,

LabBrab

**Comment by LabBrab** [comment]
Hi Anton,

I will definitely be happy to participate in the translation of other alternative endings.

Best regards,

LabBrab

[Localization.Czech.txt](https://github.com/antontimmermans/MOMEITM/files/10813845/Localization.Czech.txt)

**Comment by antontimmermans** [comment]
I have included your translation in the scenario and made minor modifications:

- I added line 104 (placing a baricade) and made an attempt of Czech translation for it. 
- I also added lines 1515+ to make sure the (new) english text and yours have an equal amount of lines in them. This is all work in progess, so not ready for translation yet. Those lines can be ignored for now, I will let you know when next ending is ready for transaltion.
 
[Localization.Czech.txt](https://github.com/antontimmermans/MOMEITM/files/10825152/Localization.Czech.txt)

Thank you very much for your hard work! it will be released and avaialble this weekend.

**Comment by LabBrab** [comment]
> I have included your translation in the scenario and made minor modifications:
> 
> * I added line 104 (placing a baricade) and made an attempt of Czech translation for it.
> * I also added lines 1515+ to make sure the (new) english text and yours have an equal amount of lines in them. This is all work in progess, so not ready for translation yet. Those lines can be ignored for now, I will let you know when next ending is ready for transaltion.
> 
> [Localization.Czech.txt](https://github.com/antontimmermans/MOMEITM/files/10825152/Localization.Czech.txt)
> 
> Thank you very much for your hard work! it will be released and avaialble this weekend.

Hi,

You translated line 104 perfectly. I also translated lines 117 and 118. I am attaching this new file.

[Localization.Czech.txt](https://github.com/antontimmermans/MOMEITM/files/10825833/Localization.Czech.txt)

**Comment by antontimmermans** [comment]
Hi @LabBrab ,

The SAO expansion for this scenario is ready to be released. 
[Localization.Czech.txt](https://github.com/antontimmermans/MOMEITM/files/11303523/Localization.Czech.txt)

Everything beyond line 1518 (eventSOAEXPANSION.text) is new and can be translated if you have time.

You could also use the translation sheet that I have created for it: https://docs.google.com/spreadsheets/d/1DL_DK5OZS0EHR_BafhTOWkCYEj9Mr49xmnR43-SfCrg/edit?usp=sharing
It may be easier to keep track of what remains to be translated. This sheet can easily be transformed back into a localization file. Just last me know when you are done.

No pressure, but I intend to release the English version next weekend. this means that the Czech version is still in Czech for the main part except for the new part in the museum. But it will still be playable.

Looking forward to hear from you.

**Comment by antontimmermans** [comment]
[Localization.Czech.txt](https://github.com/antontimmermans/MOMEITM/files/11352859/Localization.Czech.txt)
latest as released on 28-04-203
I changed in the english version the text for line item 5 (quest.description) a litlle to announce the availabiltiy of the SOA end game layout. you can check that also on the googlesheet (see link in previous posting)

**Comment by antontimmermans** [comment]
@LabBrab  The scenario now includes an additional layout that is waiting for translation. I hope you find the time to do it, The Czech community and me will be happy if you do it :)
best is if you use the translation sheet on google sheets, that way it is easier to track which lines need translation https://docs.google.com/spreadsheets/d/1DL_DK5OZS0EHR_BafhTOWkCYEj9Mr49xmnR43-SfCrg/edit#gid=1870407450 
@LabBrab

**Comment by antontimmermans** [comment]
@LabBrab the final end location is now also released. All text is added to the translation sheet. I changed the text in line 5 myself. I hope I did it correctly. Please feel free to change that text when you translate the rest.

**Comment by antontimmermans** [comment]
@LabBrab

It would be nice if you could find the time to translate the alternative endings too. The translation sheet for 'Eyes Behind the Mirror' also contains the translation for 'Return to the Mirror'. That second scenario reuses 95% of the translation from the first and requires ~15 extra lines for translation.
It's 2 translations for 1  :)

Best Regards,
Anton

**Comment by LabBrab** [comment]
Hi  Anton,

I recently updated the original file with the Czech translation. I found some inaccurate phrases there. Could you please update this translation? I only have it in the original *.txt format.

[Localization.Czech.txt](https://github.com/antontimmermans/MOMEITM/files/13850344/Localization.Czech.txt)

at the same time, today I also translated the continuation of the scenario for the "Streets of Arkham" expansion in your translate sheet on google. Do you manage to merge these two files into one and update the translation in Valkyrie

I apologize for the confusion. I had already completed the correction of the original translation and started doing the new translation in these google sheets.

LabBrab

**Comment by LabBrab** [comment]
Hi Anton again,

I also translated "Horific Journey end" in google sheets. 

I will not translate the ending for the "Path of the Serpent" yet, because this expansion has not yet been released in the Czech Republic.

**Comment by antontimmermans** [comment]
Translation for HJ end added to the scenario. PoTS remains in English
